### ISSUE TITLE
Server - solidify schema structure

### ISSUE THREAD

**Issue by irstacks** [codeforboston/snowranger#28]
Settle on organization of nodes and object attributes for storing data in Firebase and handling it through the server.

**Comment by AlexMerritt** [comment]
After dealing with the firebase implementation in angular I think it would be a good thing to store the geo cords as a single string with a comma separating the 2 values. This will keep all tables the same depth and make accessing the values much easier. When downloaded they are can be parsed into an object easily.

example: id: "-KDVjs2Bx9jV_F8Ku7iY", value: "42.034,-71.225"
