### ISSUE TITLE
Correct project structure.

### ISSUE THREAD

**Issue by aelawson** [codeforboston/snowranger#7]
Ensure Django project structure is correct.

- [ ] Static files need to be located within the app folder.
- [ ] Templates, JS, and CSS need to be modularized and not grouped together.
- [ ] Other various changes.

**Comment by aelawson** [comment]
Django app was replaced by multi-platform Ionic app (including web). Code for this component of the project has been discarded.

**Comment by akats** [comment]
Sigh :(
